In [3]:
import torch

In [4]:
randint = torch.randint(-100,100, (6,))

print(randint)

tensor([ 53,  68,   1,  38, -97, -54])


In [5]:
tensor = torch.tensor([[0.1,1.2],[4.1,1.9],[2.1,5.2]])
tensor

tensor([[0.1000, 1.2000],
        [4.1000, 1.9000],
        [2.1000, 5.2000]])

In [10]:
zeros = torch.zeros(4,2)
zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [14]:
ones = torch.ones(4,2)
ones

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [27]:
import time
import numpy as np

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [32]:
%%time

torch_rand1 = torch.rand(100,100,100,100).to(device)
torch_rand2 = torch.rand(100,100,100,100).to(device)
np_rand1 = torch.rand(100,100,100,100)
np_rand2 = torch.rand(100,100,100,100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.09696269
0.13404179
CPU times: total: 3.2 s
Wall time: 2.03 s


<timed exec>:17: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)


In [41]:
input = torch.zeros([1,2,3])
out = input.transpose(2,0)
out.shape

torch.Size([3, 2, 1])